theme: jekyll-theme-cayman
title: "Simple Heuristics as a Viable Alternative to Machine Learning-based Anomaly Detection in Industrial IoT"
description: "Simple heuristics vs. machine learning experimental evaluation paper supporting material and website."
